[package]
name = "jump_rs"
version = "1.0.0"
edition = "2024"
description = "Wake-on-LAN web server"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
tower-http = { version = "0.6", features = ["cors", "fs", "trace", "request-id", "util"] }
wake-on-lan = "0.2"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt","json"] }
regex = "1"
thiserror = "1"
parking_lot = "0.12.5"
config = "0.15"
